# Generated by Django 3.1.7 on 2021-03-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accessories_children_clothes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accessories',
            new_name='accessories_clothes',
        ),
    ]
